name: ML-Production-Deplyment
on:
  push:
    tags:
      - model-prod
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Step-Deploy
        run: |
          pip install yq
          MODEL_PATH=`yq -r .model.path artifacts.yaml`
          echo "====== Production Deployment: $MODEL_PATH ====="
